import { createContext } from "react";
const AppContext = createContext({
    spec_id: "",
    setSpecId: () => { },
    spec_name: "",
    setSpecname: () => { },
    spec_unit: "",
    setSpecUnit: () => { },
    description: "",
    setSpecDescription: () => { },
    materialDetails: [],
    setMaterialDetails: () => { },
    labourDetails: [],
    setLabourDetails: () => { },
    profit_per: 0,
    setProfit: () => { },
    additionalExpense_per: 0,
    setAdditionalExpense: () => { },
    AddEnable: false,
    setAddEnable: () => null,
    AddMaterialEnable: false,
    setAddMaterialEnable: () => null,
    AddAdditionalEnable: false,
    setAddAdditionalEnable: () => null,
    AddLabourEnable: false,
    setAddLabourEnable: () => null,
    editId: "",
    setEditId: () => { },
    editSpec_id: "",
    seteditSpec_id: () => { },
    editSpec_name: "",
    setEditSpec_name: () => { },
    editSpec_unit: "",
    setEditSpecUnit: () => { },
    editDescription: "",
    setEditDescription: () => { },
    editSpecEnable: false,
    setEditSpecEnable: () => { },
    editMaterialEnable: false,
    setEditMaterialEnable: () => { },
    edtLabourEnable: false,
    setEditLabourEnable: () => { },
    editAdditionalEnable: false,
    setEditAdditionalEnable: () => { },
    editMaterialDetails: [],
    setEditMaterialDetails: () => { },
    editlabourDetails: [],
    seteditlabourDetails: () => { },
    editadditionalExpense_per: 0,
    seteditadditionalExpense_per: () => { },
    editprofit_per: 0,
    seteditprofit_per: () => { },
    deleteSpecEnable: false,
    setDeleteSpecEnable: () => { },
    deleteId: "",
    setDeleteId: () => { }
});
export default AppContext;
