// src/interface/routes/constants/user.routes.constants.ts

export const USER_ROUTES = {
  PAYMENT_WEBHOOK: '/payment/webhook',
  UPDATE_PROFILE: '/updateprofile',
  UPDATE_PROFILE_IMAGE: '/updateprofileImage',
  CHANGE_PASSWORD: '/changepassword',
  FETCH_USER_PROJECT: '/fetchuserproject',
  FETCH_CHAT_LIST: '/fetchatList',
  FETCH_CHAT_MESSAGES: '/chats/:id',
  LOGOUT: '/logout',
  EDIT_EMAIL: '/editEmail',
  EDIT_EMAIL_RESEND: '/editEmailresend',
  EDIT_EMAIL_VERIFY: '/editEmailVerify',
  GET_SPEC: '/getSpec',
  GET_MATERIAL_BY_SPEC: '/getmaterialbySpec',
  ADD_REQUIREMENT: '/addRequirement',
  UPDATE_REQUIREMENT: '/addRequirement/:id',
  GET_ESTIMATION: '/getEstimation/:id',
  UPLOAD_ESTIMATE_IMAGE: '/uploadEstimateImage/:id',
  GET_MATERIAL_ESTIMATION: '/getMaterialEstimation/:id',
  GET_LABOUR_ESTIMATION: '/getLabourEstimation/:id',
  GET_ADDITION_ESTIMATION: '/getAdditionEstimation/:id',
  REJECT_ESTIMATION: '/rejectEstimation/:id',
  APPROVE_ESTIMATION: '/approveEstimation/:id',
  CREATE_PROJECT: '/project',
  EXPECT_IMAGE: '/expectImage/:id',
  CREATE_PAYMENT_INTENT: '/create-payment-intent',
  WALLET_PAYMENT: '/walletPayment',
  TRANSFER: '/transfer',
  REJECT_TRANSFER: '/rejectTransfer/:id',
  APPROVE_TRANSFER: '/transfer/:id',
  WALLET_HISTORY: '/wallet',
  DASHBOARD: '/dashboard',
};
