export const AUTH_ROUTES = {
  SIGNUP: '/signup',
  VERIFY_OTP: '/verifyOtp',
  RESEND_OTP: '/resendOtp',
  LOGIN: '/login',
  GOOGLE_LOGIN: '/googleLogin',
  FORGOT_OTP: '/forgotOTP',
  VERIFY_FORGOT_OTP: '/verifyForgotOtp',
  UPDATE_PASSWORD: '/updatepassword',
  PROJECT_LIST_USER: '/projectListUser',
  FETCH_EXIST_ESTIMATION: '/fetchExistEstimation/:id',
  STAGE_FETCH: '/stageFetch/:id',
  FETCH_STATUS_BASE_PROJECT: '/fetchstatusbaseproject/:status',
  REFRESH_TOKEN: '/refreshToken',
  BANNER: '/banner',
  PROJECT_STATUS_COUNT: '/projectstatuscount',
  NOTIFICATION: '/notification',
  NOTIFICATION_UPDATE: '/notification/:id',
};
