import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Route, Routes } from "react-router-dom";
import Signup from "../../pages/User/Signup";
import Otp from "../../pages/User/Otp";
import Login from "../../pages/User/Login";
import Backloginprotected from "../protectedRoute/user/backloginprotected";
import Home from "../../pages/User/Home";
import Projects from "../../pages/User/Project";
import Profile from "../../components/USER/UserFrontPage/Profile";
import ProjectDetails from "../../components/ProfileComponent/YourProjectDetails";
import OtpSend from "../../pages/User/OtpSend";
import ForgotOTP from "../../pages/User/ForgotOTP";
import NewPassword from "../../pages/User/NewPassword";
import DetailProject from "../../components/USER/UserFrontPage/ProjectDetails";
import ListProject from "../../components/USER/UserFrontPage/ListProjects";
import ProfileEdit from "../../components/ProfileComponent/ProfileEdit";
import ChangePassword from "../../components/ProfileComponent/ChangePassword";
import Chat from "../../components/ProfileComponent/Chat";
import NotFound from "../../components/NotFound";
import ProtectedRoute from "../../routes/protectedRoute/user/protectedRoute";
import ProjectProposal from "../../components/ProfileComponent/Proposal";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import Transfer from "../../components/ProfileComponent/Transfer";
import Wallet from "../../components/ProfileComponent/Wallet";
import Dashboard from "../../components/ProfileComponent/SubprofileCompponent/Dashboard";
import About from "../../pages/User/About";
import Services from "../../pages/User/Service";
const stripePromise = loadStripe("pk_test_51S7bMD1P84WAbTJTerojk1ff5MKXMgAJX2YZ5XQPA1DJHsraJm1YSjr5oGTYRuDbyoSPakUJfx7FT7NMGJUVexwm00fPjEzze7");
export const UserRoutes = () => {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/signup", element: _jsx(Signup, {}) }), _jsx(Route, { path: "/otp", element: _jsx(Otp, {}) }), _jsx(Route, { path: "/otpsend", element: _jsx(OtpSend, {}) }), _jsx(Route, { path: "/forgototp", element: _jsx(ForgotOTP, {}) }), _jsx(Route, { path: "/newPassword", element: _jsx(NewPassword, {}) }), _jsx(Route, { path: "/login", element: _jsx(Backloginprotected, { children: _jsx(Login, {}) }) }), _jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/project", element: _jsx(Projects, {}) }), _jsx(Route, { path: "/about", element: _jsx(About, {}) }), _jsx(Route, { path: "/service", element: _jsx(Services, {}) }), _jsx(Route, { path: "/projectDetail", element: _jsx(DetailProject, {}) }), _jsx(Route, { path: "/projectlist", element: _jsx(ListProject, {}) }), _jsx(Route, { path: "/proposal", element: _jsx(ProtectedRoute, { children: _jsx(ProjectProposal, {}) }) }), _jsxs(Route, { path: "/profile", element: _jsx(ProtectedRoute, { children: _jsx(Profile, {}) }), children: [_jsx(Route, { path: "", element: _jsx(ProfileEdit, {}) }), _jsx(Route, { path: "dashboard", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "project", element: _jsx(Elements, { stripe: stripePromise, children: _jsx(ProjectDetails, {}) }) }), _jsx(Route, { path: "change-password", element: _jsx(ChangePassword, {}) }), _jsx(Route, { path: "chat", element: _jsx(Chat, {}) }), _jsx(Route, { path: "transfer", element: _jsx(Transfer, {}) }), _jsx(Route, { path: "wallet", element: _jsx(Wallet, {}) })] }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }));
};
