import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PencilIcon, TrashIcon } from "@heroicons/react/24/outline";
import ReUsableAddButton from "../../../components/ReUsableComponents/ReUsableAddButton";
import ReUsablePagination from "../../../components/ReUsableComponents/ReUsablePagination";
import ReUsableSearch from "../../../components/ReUsableComponents/ReUsableSearch";
import Loading from "../../../components/Loading";
import { useState } from "react";
function MaterialList({ setEnable, enable, materialData, setDeleteEnable, setDeleteId, setPage, setSearch, search, page, totalPage, setEditEnable, setEditId, editEnable, loadOn }) {
    if (enable || editEnable)
        return null;
    return (_jsx("div", { className: "p-6 sm:p-8 min-h-screen bg-gray-900", children: _jsxs("div", { className: "bg-gray-800/90 backdrop-blur-sm shadow-2xl rounded-2xl p-6 sm:p-8 max-w-6xl mx-auto border border-gray-700/50", children: [_jsxs("div", { className: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6 mb-8", children: [_jsx(ReUsableSearch, { search: search, setSearch: setSearch, item: "material" }), _jsx(ReUsableAddButton, { addFuntion: () => setEnable(true), item: "Material" })] }), loadOn && (_jsx("div", { className: "absolute inset-0 bg-black/40 flex items-center justify-center rounded-xl pointer-events-none z-50", children: _jsx(Loading, {}) })), _jsxs("div", { className: "overflow-x-auto rounded-xl border border-gray-700/50", children: [_jsxs("table", { className: "min-w-full text-sm text-left bg-gray-800/50", children: [_jsx("thead", { className: "bg-gray-800/70 text-gray-200 uppercase text-xs font-semibold tracking-wider", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-4", children: "SL No" }), _jsx("th", { className: "px-6 py-4", children: "Material Name" }), _jsx("th", { className: "px-6 py-4", children: "Category" }), _jsx("th", { className: "px-6 py-4", children: "Brand" }), _jsx("th", { className: "px-6 py-4", children: "Unit" }), _jsx("th", { className: "px-6 py-4", children: "Unit Rate" }), _jsx("th", { className: "px-6 py-4 text-center", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-700/50", children: materialData.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "text-center py-12 text-gray-400 text-sm font-medium", children: "No materials found." }) })) : (materialData.map((element, index) => (_jsxs("tr", { className: "hover:bg-gray-700/50 transition-colors duration-150", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-200", children: (index + 1) + (page * 5) }), _jsx("td", { className: "px-6 py-4 text-gray-200", children: element.material_name }), _jsx("td", { className: "px-6 py-4 text-gray-200", children: element.categoryDetails[0]?.category_name || "-" }), _jsx("td", { className: "px-6 py-4 text-gray-200", children: element.brandDetails[0]?.brand_name || "-" }), _jsx("td", { className: "px-6 py-4 text-gray-200", children: element.unitDetails[0]?.unit_name || "-" }), _jsx("td", { className: "px-6 py-4 text-gray-200", children: element.unit_rate }), _jsxs("td", { className: "px-6 py-4 text-center space-x-3", children: [_jsx("button", { className: "text-yellow-400 hover:text-yellow-300 p-2 rounded-md hover:bg-gray-600/50 transition-all duration-200", "aria-label": `Edit material ${element.material_name}`, onClick: () => {
                                                            setEditEnable(true);
                                                            setEditId(element._id);
                                                        }, children: _jsx(PencilIcon, { className: "h-5 w-5" }) }), _jsx("button", { onClick: () => {
                                                            setDeleteEnable(true);
                                                            setDeleteId(element._id);
                                                        }, className: "text-red-400 hover:text-red-300 p-2 rounded-md hover:bg-gray-600/50 transition-all duration-200", "aria-label": `Delete material ${element.material_name}`, children: _jsx(TrashIcon, { className: "h-5 w-5" }) })] })] }, element._id)))) })] }), _jsx(ReUsablePagination, { page: page, setPage: setPage, totalPage: totalPage })] })] }) }));
}
export default MaterialList;
