import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { downloadPDF } from "../../../../api/downloadPDF";
function MaterialLabourAnalysis({ Data, total, setMaterialPage, materialPage, heading }) {
    return (_jsxs("div", { className: "w-full max-w-7xl mx-auto p-6 bg-gradient-to-b from-slate-900 to-slate-800 rounded-xl shadow-lg border border-slate-700/50", children: [_jsx("div", { className: "flex justify-between items-center mb-6", children: _jsx("h2", { className: "text-2xl font-bold text-white border-b border-slate-600 pb-3 tracking-tight", children: heading }) }), _jsx("div", { className: "flex justify-end mb-4", children: _jsx("button", { onClick: () => downloadPDF(Data), className: "px-4 py-2 bg-slate-800/50 text-slate-300 rounded-md hover:bg-orange-500 hover:text-white transition-colors duration-200", children: "Download PDF" }) }), _jsx("div", { className: "overflow-x-auto", children: Data.length === 0 ? (_jsxs("div", { className: "text-center py-12 text-slate-400", children: [_jsx("p", { className: "text-lg font-medium", children: "No data available" }), _jsx("p", { className: "text-sm", children: "Please check back later or add new projects." })] })) : (_jsxs("table", { className: "w-full border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-slate-800/70 text-slate-300 uppercase text-xs font-semibold tracking-wider", children: [_jsx("th", { className: "py-4 px-6 text-left", children: "SL No" }), _jsx("th", { className: "py-4 px-6 text-left", children: "Project Name" }), _jsx("th", { className: "py-4 px-6 text-right", children: "Budgeted Cost" }), _jsx("th", { className: "py-4 px-6 text-right", children: "Actual Expense" }), _jsx("th", { className: "py-4 px-6 text-right", children: "Variance" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-700/50", children: Data.map((element, index) => {
                                const variance = element.budgeted_cost - element.actual_expense;
                                return (_jsxs("tr", { className: "hover:bg-slate-700/50 transition-colors duration-150", children: [_jsx("td", { className: "py-4 px-6 text-slate-400", children: index + 1 }), _jsx("td", { className: "py-4 px-6 text-white font-medium", children: element.project_name }), _jsxs("td", { className: "py-4 px-6 text-right text-white", children: ["\u20B9", element.budgeted_cost.toLocaleString()] }), _jsxs("td", { className: "py-4 px-6 text-right text-white", children: ["\u20B9", element.actual_expense.toLocaleString()] }), _jsxs("td", { className: `py-4 px-6 text-right font-medium ${variance >= 0 ? "text-orange-400" : "text-red-400"}`, children: ["\u20B9", Math.abs(variance).toLocaleString(), " ", variance >= 0 ? "(Under)" : "(Over)"] })] }, index));
                            }) })] })) }), total.length >= 1 && (_jsxs("div", { className: "mt-6 flex justify-center gap-2", children: [_jsx("button", { onClick: () => setMaterialPage((prev) => Math.max(prev - 1, 0)), disabled: materialPage === 0, className: "px-3 py-1 bg-slate-800/50 text-slate-300 rounded-md hover:bg-orange-500 hover:text-white transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed", children: "Previous" }), total.map((_, index) => (_jsx("button", { onClick: () => setMaterialPage(index), className: `px-3 py-1 rounded-md transition-colors duration-200 ${materialPage === index
                            ? "bg-teal-600 text-white"
                            : "bg-gray-700 text-gray-300 hover:bg-teal-500 hover:text-white"}`, children: index + 1 }, index))), _jsx("button", { onClick: () => setMaterialPage((prev) => Math.min(prev + 1, total.length - 1)), disabled: materialPage === total.length - 1, className: "px-3 py-1 bg-slate-800/50 text-slate-300 rounded-md hover:bg-orange-500 hover:text-white transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed", children: "Next" })] }))] }));
}
export default MaterialLabourAnalysis;
